### ISSUE TITLE
No valid ES module

### ISSUE THREAD

**Issue by GeneralMine** [BerkinAKKAYA/svelte-image-gallery#10]
When I'm using this npm module with sveltekit I will get these messages while compiling:
`svelte-image-gallery doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact 
the package author to fix.`

It still works, so nothing has to be done urgently, but it remains to be necessary in the future

**Comment by BerkinAKKAYA** [comment]
Hi @GeneralMine. I converted the entry point to an mjs file and it seems to have solved it. Let me know if you are still getting the same warning please. Thanks a lot for the feedback!

**Comment by ezfe** [comment]
@BerkinAKKAYA When you did this, you forgot to update the `main` field in package.json

**Comment by BerkinAKKAYA** [comment]
Thanks @ezfe, fixed it ✅
