### ISSUE TITLE
NPM Package Outdated?

### ISSUE THREAD

**Issue by AidanG1** [BerkinAKKAYA/svelte-image-gallery#5]
I am trying to use the handleClick option with the code from the readme. Here is a repl: [https://svelte.dev/repl/b8a0410412314c299fd02278bb414df2?version=3.24.1](https://svelte.dev/repl/b8a0410412314c299fd02278bb414df2?version=3.24.1). When I run it, nothing console logs. However, when I paste in the code from this repo, it console logs [https://svelte.dev/repl/e5974a7b08c44c978acdd41ac4353bbc?version=3.24.1](https://svelte.dev/repl/e5974a7b08c44c978acdd41ac4353bbc?version=3.24.1). Based on this, I think the NPM package is outdated. Additionally, the last commit on the Github is from 9 months ago while the last NPM update is a year ago [https://www.npmjs.com/package/svelte-image-gallery](https://www.npmjs.com/package/svelte-image-gallery). Thanks for taking a look at this.

**Comment by BerkinAKKAYA** [comment]
Hi. It's true that this package haven't been updated for almost a year but i will spend some time to update & refactor it soon. Thanks for your interest!

**Comment by BerkinAKKAYA** [comment]
Some refactors and improvements have been published and more contributions/recommendations are welcome!
